# Generated by Django 2.2 on 2019-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
            ],
        ),
    ]
